#include "day1.h"

/**
 * @brief
 * This function calculates the distance
 * between the values of both lists
 * 
 * @arg list_one: left column numbers
 * @arg list_two: right column numbers
 * These lists are generated by reading
 * the input file
 * 
 * @returns the sum of these distances
 */
int part_one(list_t *list_one, list_t *list_two) 
{

    int result = 0;
    int min1 = 0;
    int min2 = 0;

    while (list_one != NULL && list_two != NULL) 
    {
        min1 = pop(&list_one)->value;
        min2 = pop(&list_two)->value;
        printf("min1: %d, min2: %d\n", min1, min2);

        int dist = abs(min1 - min2);
        printf("dist: %d\n", dist);

        result = result + dist;
    }

    return result;
}

int part_two(list_t *list_one, list_t *list_two) 
{
    int result = 0;
    
    while (list_one != NULL) 
    {
        list_t *tmp = pop(&list_one);
        int value = tmp->value;
        int count = 0;

        count = occurences(list_two, value);
        result = result + (count * value);

    }

    return result;
}

